### ISSUE TITLE
MathJax config loaded but not rendering properly in pages that use it

### ISSUE THREAD

**Issue by mhl10** [arXiv/arxiv-marxdown#14]
The MathJax script and corresponding configuration are being loaded, but there is an issue with rendering:

<img width="1125" alt="screenshot 2019-02-12 10 10 57" src="https://user-images.githubusercontent.com/746253/52645300-8316af80-2eae-11e9-9a40-98f5fc26578d.png">

The configuration looks OK and appears to match what is being used on the classic https://arxiv.org/help/mathjax page so it's not immediately clear what's going on.

This issue may be more appropriate for https://github.com/arXiv/arxiv-base since MathJax is being loaded in base templates.

**Comment by erickpeirson** [comment]
Looks like they're getting wrapped in ``<span class="ignore_mathjax">...</span>`` ... deliberate sabotage!
